### ISSUE TITLE
import cuda_sparse_ops

### ISSUE THREAD

**Issue by AArutoria** [POSTECH-CVLab/FastPointTransformer#10]
Thanks to the author for such quality code. I have some questions for the author,
in the sparse_ops.py file. 
import cuda_sparse_ops
keeps reporting errors. 
How to solve it? ? ?
And how to run setup.py in src.cuda_ops？？？？？？

**Comment by chrockey** [comment]
Hi,

I think the cuda_sparse_ops is not properly installed.
Could you check the conda path in setup.sh is correct?

**Comment by AArutoria** [comment]
Thank you for your answer. I have solved this problem.
