### ISSUE TITLE
About the environment

### ISSUE THREAD

**Issue by lishuai-97** [POSTECH-CVLab/FastPointTransformer#13]
Could you share some environmental information?  I can successfully install pytorch according to setup.py, but there is a conflict when I install openblas-devel.

**Comment by chrockey** [comment]
Hi @lishuai-97,

I've just uploaded the environment.yaml file to the master branch.
You may check the versions of the main packages (e.g., PyTorch, PyTorch Lightning, ...) there.

**Comment by lishuai-97** [comment]
Thank you for your timely reply. I will try to solve this problem.
