### ISSUE TITLE
Code for 3d object detection

### ISSUE THREAD

**Issue by Kyfafyd** [POSTECH-CVLab/FastPointTransformer#2]
Thanks for the great work!
I would like to learn if the code for 3d object detection is released?

**Comment by chrockey** [comment]
Hi,

Thank you for your interest in our work!
I've added a link for [another GitHub repo](https://github.com/chrockey/FastPointTransformer-VoteNet) to README.md, which contains 3D object detection codes.
The reason why I did not include those codes in this repo is that there are some LICENSE conflicts between ours (MIT) and Torch-Points3D (BSD) which we used for 3D object detection.

Chunghyun

**Comment by Kyfafyd** [comment]
Thanks!
