### ISSUE TITLE
Could it utilize the inter-frame information?

### ISSUE THREAD

**Issue by artofstate** [POSTECH-CVLab/FastPointTransformer#5]
Hi,Thanks for your great work first,but I have some questions about the attention block.
For example, I set batch size = 2, how can i find the query voxels around both two frames.

**Comment by chrockey** [comment]
Hi,

If I understand your question correctly, your question is whether finding neighbor voxels from two different voxel grids (or point clouds) is available or not.
The short answer is "yes", but you may need to modify or implement some codes.

Here is an example pseudo-code.
```
# A: ME.SparseTensor, B: ME.SparseTensor
B' = ME.SparseTensor(B.F, torch.cat(A.C[:, 0], B.C[:, 1:])) # a new sparse tensor
C = ME.cat(A, B')
D = your_function(C)
```
The above code may enable your function to find neighbor voxels across different voxel grids (in this case A and B).
Note that the above code is just for reference. You may need to modify it.

For the temporal kernel, [this link](https://github.com/chrischoy/SpatioTemporalSegmentation/blob/4afee296ebe387d9a06fc1b168c4af212a2b4804/models/res16unet.py#L18) also helps your understanding.
