### ISSUE TITLE
How to get the access to wandb?

### ISSUE THREAD

**Issue by Tomoki-0526** [POSTECH-CVLab/FastPointTransformer#8]
An error is reported when training the dataset, saying "Error while calling W&B API: permission denied (<Response [403]>)". I checked the documentation of wandb and it says  I don't have the project permissions. I want to know how to get the permission, thanks for your help!

**Comment by chrockey** [comment]
Hi,

Sorry for the late reply.
I'm not sure what caused that error since I've not seen that error.
Could you try to change the project name in the config file?

**Comment by Tomoki-0526** [comment]
Thanks for your reply and I've found the solution by taking wandb offline

**Comment by lucksonn** [comment]
> Thanks for your reply and I've found the solution by taking wandb offline

Could you please tell me how to do this？Thx a lot!!!

**Comment by Tomoki-0526** [comment]
@lucksonn Actually I‘ve almost forgotten how to do that hhah, and I'm not running this program now. I think you can try some command of wandb, such as _wandb offline_ or something like this.

**Comment by lucksonn** [comment]
ok，thank you！I ve changed the entity to my own username. And it worked!
