### ISSUE TITLE
Training Log

### ISSUE THREAD

**Issue by aoligei178** [POSTECH-CVLab/FastPointTransformer#9]
Hellow! Thank you for your awesome work!
I find that it takes 20 hours on A100 to train your model. Could I have a look at your training log on S3DIS?

**Comment by chrockey** [comment]
Hi,

Thanks for your interest in our work 😄.
As mentioned in [this issue](https://github.com/POSTECH-CVLab/FastPointTransformer/issues/1#issuecomment-1102915885), training Fast Point Transformer on S3DIS takes 20 hours.
Here is the training log for [the released checkpoint](https://postechackr-my.sharepoint.com/:u:/g/personal/p0125ch_postech_ac_kr/ER8KwMTzqAxAvK9KeOZ9U_IBuCAuv4hP6zOWD-3HNO6Xeg?download=1):
- [val_best_mIoU](https://wandb.ai/chrockey/fpt-release/reports/val_best_mIoU-22-08-15-22-08-30---VmlldzoyNDc2NjQ4?accessToken=iue8l39ywuw4jfy9crw5mybysbc3acvpeq2cqoh3vemunldnk3u8ztizc2pyo001)
- [val_loss](https://wandb.ai/chrockey/fpt-release/reports/val_loss-22-08-15-22-08-42---VmlldzoyNDc2NjU0?accessToken=ftb0an6zr9iumq13rwtmas5ok7wzkbd3gjweb59997q4aj1hqwtul9p8knnpawul)
- [val_mIoU](https://wandb.ai/chrockey/fpt-release/reports/val_mIoU-22-08-15-22-08-31---VmlldzoyNDc2Njcy?accessToken=cva5ejpkt4xwx2nw3bq11gwivu1pvj5ph6hkdwbjmmf6ocdm5db86vpgr72k2ugp)
- [val_mAcc](https://wandb.ai/chrockey/fpt-release/reports/val_mAcc-22-08-15-22-08-56---VmlldzoyNDc2Njgw?accessToken=t6hwoywwyex65g60a9msareb10os9qjkqocs30o8n2e875h7i9h6vljeotangrw0)
- [train_loss](https://wandb.ai/chrockey/fpt-release/reports/train_loss-22-08-15-22-08-33---VmlldzoyNDc2NjYy?accessToken=sj0a2ttti04zhdb51aq06zbserl463h69hhvp5zhae0j03o2wb70y8whz3g6zgj6)
- [learning_rate](https://wandb.ai/chrockey/fpt-release/reports/lr-SGD-22-08-15-22-08-33---VmlldzoyNDc2NjU4?accessToken=81e4gq5tdyrbilpxa3iizj6m1ruhyhcsvwf4nsw5q44sfwmq6dd0kqmjqt5s24d3)
- [train_epoch](https://wandb.ai/chrockey/fpt-release/reports/epoch-22-08-15-22-08-53---VmlldzoyNDc2NjYx?accessToken=x7qjqnbx5vrbpju33cv2tov4kpgxx4l8oydm86gpy6d1ggsa0qmrqu23oiifu4fx)
